// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_images from "./routes/api/images.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $index from "./routes/index.tsx";
import * as $upload from "./routes/upload.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $EntryUploader_Can_Work_txt from "./islands/EntryUploader (Can Work).txt.tsx";
import * as $EntryUploader_Promising_txt from "./islands/EntryUploader (Promising).txt.tsx";
import * as $EntryUploader from "./islands/EntryUploader.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/images.ts": $api_images,
    "./routes/api/joke.ts": $api_joke,
    "./routes/index.tsx": $index,
    "./routes/upload.tsx": $upload,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/EntryUploader (Can Work).txt.tsx": $EntryUploader_Can_Work_txt,
    "./islands/EntryUploader (Promising).txt.tsx": $EntryUploader_Promising_txt,
    "./islands/EntryUploader.tsx": $EntryUploader,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
